"""
Django settings for AKalan project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8&tg9svnx0!34y$1inl)(4ob=r3=ie(+7eb&w6z)rck84jrl3+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'comptes',  # Doit être avant admin pour que nos templates soient prioritaires
    'cours',
    'devoirs',
    'enseignants',
    'etudiants',
    'django.contrib.admin',  # Déplacé après comptes
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AKalan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AKalan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'AKalan',
        'USER': 'root',
        'PASSWORD': 'root',  # Mot de passe par défaut de MAMP
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'unix_socket': '/Applications/MAMP/tmp/mysql/mysql.sock',  # Socket MySQL de MAMP
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Utilisateur personnalisé
AUTH_USER_MODEL = 'comptes.Utilisateur'

# Configuration de l'authentification
# LOGIN_URL est utilisé par @login_required quand aucun login_url n'est spécifié
# On le définit vers la page d'accueil qui redirige selon le rôle
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'

# fichiers média
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fichiers statiques des apps
STATICFILES_DIRS = [
    BASE_DIR / 'theme' / 'static',
]

# Tailwind CSS Configuration
TAILWIND_APP_NAME = 'theme'

# Configuration Email
# Pour envoyer de vrais emails, configurez ces paramètres :
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Pour Gmail, utilisez 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'boukaribaradji01@gmail.com'  # Remplacez par votre adresse email Gmail
EMAIL_HOST_PASSWORD = 'iawy oyzy todl hhaa'  # Remplacez par votre mot de passe d'application Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # L'email sera envoyé depuis cette adresse

# URL du site (pour les liens dans les emails)
SITE_URL = 'http://127.0.0.1:8000'

# Note : Pour Gmail, vous devez :
# 1. Activer l'authentification à deux facteurs sur votre compte Google
# 2. Créer un "Mot de passe d'application" :
#    - Allez sur https://myaccount.google.com/apppasswords
#    - Sélectionnez "Autre (nom personnalisé)" et entrez "AKalan"
#    - Copiez le mot de passe généré et utilisez-le dans EMAIL_HOST_PASSWORD
# 3. Si vous utilisez un autre fournisseur email, ajustez EMAIL_HOST et EMAIL_PORT :
#    - Outlook/Hotmail: smtp-mail.outlook.com, port 587
#    - Yahoo: smtp.mail.yahoo.com, port 587
#    - Autre: consultez la documentation de votre fournisseur
