# Generated by Django 6.0 on 2025-12-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_classe_utilisateur_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.classe', verbose_name='Classe'),
        ),
    ]
