# Generated by Django 6.0 on 2025-12-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_utilisateur_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='enseignant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant responsable'),
        ),
    ]
