# Generated by Django 6.0 on 2025-12-24 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_classe_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='classe',
            name='enseignants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'enseignant'}, related_name='classes_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='Enseignants'),
        ),
    ]
